//{{NO_DEPENDENCIES}}
// Von Microsoft Visual C++ generierte Includedatei.
// Verwendet durch ZyHelperBeta.rc
//
#define IDD_DIALOG1                     101
#define IDB_IP                          106
#define IDB_SPRINT                      108
#define IDB_FALTER                      109
#define IDB_WC                          110
#define IDB_BERSERKER                   111
#define IDB_BOH                         112
#define IDB_EPIPHANY                    113
#define IDB_MANTRAOFCONVICTION          114
#define IDB_MANTRAOFHEALING             115
#define IDB_SWEEPINGWIND                116
#define IDB_BONEARMOR                   117
#define IDB_LOTD                        118
#define IDB_POTION                      119
#define IDB_BLACKHOLE                   121
#define IDB_DISINTEGRATE                122
#define IDB_ELECTROCUTE                 123
#define IDB_METEOR                      124
#define IDB_WAVEOFFORCE                 125
#define IDB_MAGICWEAPON                 126
#define IDB_STORMARMOR                  127
#define IDB_PREPARATION                 129
#define IDB_RAINOFVENGEANCE             130
#define IDB_VENGEANCE                   131
#define IDB_SKELEMAGE                   132
#define IDB_DEVOUR                      133
#define IDB_SIM                         134
#define IDB_ARCANEBLAST                 135
#define IDB_ARCHON                      136
#define IDB_EXPLOSIVEBLAST              137
#define IDB_BLOODNOVA                   138
#define IDB_BLINDINGFLASH               139
#define IDC_IPCHECK                     1007
#define IDC_WCCHECK                     1008
#define IDC_FALTERCHECK                 1009
#define IDC_BERSERKERCHECK              1010
#define IDC_EPIPHANYCHECK               1011
#define IDC_SPRINTCHECK                 1012
#define IDC_MANTRAHEALINGCHECK          1013
#define IDC_LANDOFTHEDEADCHECK          1014
#define IDC_SWEEPINGWINDCHECK           1015
#define IDC_BONEARMORCHECK              1016
#define IDC_BOHCHECK                    1017
#define IDC_IPHOTKEY                    1018
#define IDC_WCHOTKEY                    1019
#define IDC_FALTERHOTKEY                1020
#define IDC_BERSERKERHOTKEY             1021
#define IDC_SPRINTHOTKEY                1022
#define IDC_EPIPHANYHOTKEY              1023
#define IDC_MANTRAHEALINGHOTKEY         1024
#define IDC_SWEEPINGWINDHOTKEY          1025
#define IDC_BOHHOTKEY                   1026
#define IDC_MANTRACONVICTIONCHECK       1027
#define IDC_MANTRACONVICTIONHOTKEY      1028
#define IDC_LANDOFTHEDEADHOTKEY         1029
#define IDC_BONEARMORHOTKEY             1030
#define IDC_IP                          1031
#define IDC_WC                          1032
#define IDC_FALTER                      1033
#define IDC_BERSERKER                   1034
#define IDC_SPRINT                      1035
#define IDC_EPIPHANY                    1036
#define IDC_MANTRAOFHEALING             1037
#define IDC_SWEEPINGWIND                1038
#define IDC_BOH                         1039
#define IDC_MANTRAOFCONVICTION          1040
#define IDC_LOTD                        1041
#define IDC_BONEARMOR                   1042
#define IDC_ACTIVERUNNING               1043
#define IDC_POTIONCHECK                 1044
#define IDC_POTIONTHOTKEY               1045
#define IDC_SPRINT2                     1046
#define IDC_UPPERBOUND                  1047
#define IDC_LOWERBOUND                  1048
#define IDC_TIME                        1049
#define IDC_COE                         1050
#define IDC_WAVEOFFORCE                 1051
#define IDC_ELECTROCUTE                 1052
#define IDC_METEOR                      1053
#define IDC_DISINTEGRATE                1054
#define IDC_BLACKHOLE                   1055
#define IDC_STORMARMOR                  1056
#define IDC_MAGICWEAPON                 1057
#define IDC_BLACKHOLECHECK              1058
#define IDC_STORMARMORCHECK             1059
#define IDC_MAGICWEAPONCHECK            1060
#define IDC_MACROCHECK                  1061
#define IDC_WAVEOFFORCEHOTKEY           1062
#define IDC_ELECTROCUTEHOTKEY           1063
#define IDC_METEORHOTKEY                1064
#define IDC_DISINTEGRATEHOTKEY          1065
#define IDC_BLACKHOLEHOTKEY             1066
#define IDC_STORMARMORHOTKEY            1067
#define IDC_MAGICWEAPONHOTKEY           1068
#define IDC_MACROHOTKEY                 1069
#define IDC_MACROACTIVE                 1070
#define IDC_TIMINGKEY                   1071
#define IDC_TOGGLEKEY                   1072
#define IDC_VENGEANCE                   1073
#define IDC_RAINOFVENGEANCE             1074
#define IDC_PREPARATION                 1075
#define IDC_VENGEANCECHECK              1076
#define IDC_RAINOFVENGEANCECHECK        1077
#define IDC_PREPARATIONCHECK            1078
#define IDC_VENGEANCEHOTKEY             1079
#define IDC_RAINOFVENGEANCEHOTKEY       1080
#define IDC_PREPARATIONHOTKEY           1081
#define IDC_ACTIVE                      1082
#define IDC_SKELEMAGE                   1083
#define IDC_SKELEMAGECHECK              1084
#define IDC_SKELEMAGEHOTKEY             1085
#define IDC_DEVOUR                      1086
#define IDC_DEVOURCHECK                 1087
#define IDC_DEVOURHOTKEY                1088
#define IDC_SIM                         1089
#define IDC_SIMCHECK                    1090
#define IDC_SIMHOTKEY                   1091
#define IDC_SECONDSIM                   1092
#define IDC_HEXING                      1093
#define IDC_ARCHONECHECK                1094
#define IDC_ARCHON                      1095
#define IDC_ARCHONHOTKEY                1096
#define IDC_ARCANEBLAST                 1097
#define IDC_ARCANEBLASTCHECK            1098
#define IDC_ARCANEBLASTHOTKEY           1099
#define IDC_EXPLOSIVEBLAST              1100
#define IDC_EXPLOSIVEBLASTCHECK         1101
#define IDC_EXPLOSIVEBLASTHOTKEY        1102
#define IDC_BLOODNOVA                   1103
#define IDC_BLOODNOVACHECK              1104
#define IDC_BLOODNOVAHOTKEY             1105
#define IDC_FORCESTANDSTILLHOTKEY       1106
#define IDC_POSITIONHOTKEY              1107
#define IDC_POSITIONSAVED               1108
#define IDC_BLINDINGFLASH               1109
#define IDC_BLINDINGFLASHCHECK          1110
#define IDC_BLINDINGFLASHHOTKEY         1111
#define IDC_MACROHOTKEY2                1112
#define IDC_CHANNELHOTKEY               1112

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        140
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1048
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
